### ISSUE TITLE
Add new specialized packages?

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#106]
https://www.tidyverse.org/blog/2020/04/parsnip-adjacent/

To:

https://www.tidymodels.org/packages/#specialized-packages

**Comment by juliasilge** [comment]
These don't have pkgdown sites yet, so I say we keep this as a post-launch task to come back to later.

**Comment by topepo** [comment]
Yeah. I didn't want to make them and just change them a few days later.
