### ISSUE TITLE
Update pkgdown sites

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#111]
``` 
part_of: <a href="https://github.com/tidymodels">tidymodels</a>
```
to...

``` 
part_of: <a href="https://www.tidymodels.org">tidymodels</a>
```

For example: 
https://github.com/tidymodels/parsnip/blob/master/_pkgdown.yml#L4
https://github.com/tidymodels/tune/blob/master/_pkgdown.yml#L4
https://github.com/tidymodels/rsample/blob/master/_pkgdown.yml#L6
https://github.com/tidymodels/workflows/blob/master/_pkgdown.yml#L4

etc. ;)

**Comment by juliasilge** [comment]
I believe the only existing tidymodels pkgdown site that has not been ported over is [butcher](https://tidymodels.github.io/butcher/).

**Comment by apreshill** [comment]
Not sure what the plan is for the URL vs pkgdown theme, but broom doesn't have the tidymodels theme currently: https://broom.tidymodels.org/
