### ISSUE TITLE
Change wording for required packages 

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#118]
The current scripts used in `start/` and `learn/` starts: "This article requires that you have the following packages installed:"

Could we make it slightly more reader friendly?

Proposed: "To use the code in this article, you will need to install the following packages:"

Open to any other wording suggestions.

**Comment by juliasilge** [comment]
I think this is a great idea. If you want to focus on edits for `/start` including this I will take care of this in `/learn`.

**Comment by apreshill** [comment]
Here is my new snippet from `common.R`:

```
req_pkgs <- function(x, what = "To use code in this article, ") {
  x <- sort(x)
  x <- knitr::combine_words(x, and = " and ")
  paste0(
    what,
    " you will need to install the following packages: ",
    x, "." 
  )
}
```

**Comment by apreshill** [comment]
Updated now in all 5 articles
