### ISSUE TITLE
add basic inference with infer package example?

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#12]
The infer package is in tidymodels, and it might be helpful to link out to it from tidymodels.org so folks who don't do ML can be aware. Lots of existing examples here:
https://infer.netlify.com/articles/

**Comment by topepo** [comment]
I'm drop them a line and see if they would like to (or what they would like to) contribute.

**Comment by topepo** [comment]
tidymodels/infer#295
