### ISSUE TITLE
Final review: start/ section

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#127]
After going deep on articles in the start section, I'm parking some issues here that are small and that I can quickly fix before launch:

1. ~~Make [homepage](https://www.tidymodels.org/start/) more explicit that good for those who are new to modeling or new to tidymodels.~~

1. ~~Check the width arg- I'm sometimes seeing an annoying horizontal scroll bar on single pages. (on models, recipes, resampling)~~ this was due to workflows overriding `options(width =80)` when printing; https://github.com/tidymodels/workflows/issues/38

   ```
   .article-content {
	/* overflow-x: auto; */
       overflow-x: hidden;
   }

   pre {
         white-space: pre-wrap;
         max-width: 100%;
   }
   ```

1. Go through and use **bold** for new terms and _italics_ for emphasis

1. Check chunks for using R printing options for tibbles- some are too long

1. Make md defined links for all links out to pkgdown sites, in prep for those urls changing en masse

1. Do final cross-check on all anchor link headings and urls across articles for consistency

1. ~~Remove modeling packages from package loading chunks per @topepo~~

1. ~~Beg for `theme_minimal()`~~ 😸 (confusing with facetted plots)

1. ~~Update ggplot2 colors to be viridis plasma palette (no extra dependencies; better palettes for common types of colorblindness); see about using same font as site (lato) (but don't want to use showtext d/t renv not being able to install)~~

1. ~~Add anchorized header links (currently working in a dev branch on personal repo) to improve navigability (see: https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726/14)~~

1. ~~Small CSS change for inline code:~~

```
code {
	font-size: 1rem;
}
```

**Comment by juliasilge** [comment]
I tend to think your number 1 is pretty good already; I like how it is worded to avoid saying "this is for beginners" but is welcoming and focuses on getting started.

**Comment by juliasilge** [comment]
I believe I got number 7 in #131.
