### ISSUE TITLE
Issues for Max for recipes/flights post

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/tidymodels.org-legacy#13]
This example is really shaping up well. 🙌 Super clear and laid out well. I have several items I think would improve folks' ability to absorb this

- [x] One line says "To train this model, each predictor will need to be in a numeric format." but this is regular logistic regression. Does it _need_ to be numeric? Can we say why? Or can we change this sentence to just say this is what we're doing?
- [x] A line says that recipes do not automatically create dummy variables and I'm left feeling like you should tell me why. A footnote? Just like a sentence.
- [x] "Note that the `dplyr` selectors don't like column names." I don't understand what this is supposed to mean. 🙈

**Comment by topepo** [comment]
That last one was supposed to mean that we can also select by roles or data types.
