### ISSUE TITLE
Wide printing of output that ignores options(width)

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#133]
Spotted:

https://www.tidymodels.org/learn/models/parsnip-ranger-glmnet/ (parsnip)

https://www.tidymodels.org/start/resampling/#modeling (parsnip)

https://www.tidymodels.org/learn/models/sub-sampling/ (workflow)

https://www.tidymodels.org/learn/work/bayes-opt/#sequential-tuning (tune)

**Comment by juliasilge** [comment]
As discussed in tidymodels/workflows#38, we can add this in the setup chunk:

> Setting the cli.width with `options(cli.width = 20)` is a more permanent solution. I don't think there is anything else to do here.

**Comment by juliasilge** [comment]
Closed in #184
