### ISSUE TITLE
Statistical model in "Build a model" is not an ANCOVA

### ISSUE THREAD

**Issue by cedricbatailler** [tidymodels/tidymodels.org-legacy#139]
In the Get started section of the tidymodels.org site, the Build a model section refers to the model used as an ANCOVA (see https://github.com/tidymodels/tidymodels.org/blob/4e23168bf7e92ef49f2ed58b311d6237ea6f7cdc/content/start/models/index.Rmarkdown#L86). However, a model with a `y ~ x1 * x2` is not an ANCOVA model, but a multiple regression with an interaction term model (an ANCOVA model would look like this `y ~ x1 + x2`). This make quite a few difference in terms of modeling as an ANCOVA model does not allow the effect of `x1` to differ according to `x2` values, while a model with a regression term allow this (see the homogeneity of regression slopes in the ANCOVA model https://en.wikipedia.org/wiki/Analysis_of_covariance#Assumption_5:_homogeneity_of_regression_slopes). 

I would suggest not to use the ANCOVA term as such model does not allow for interaction and it could be a source of confusion for readers familiar with ANCOVA.

**Comment by juliasilge** [comment]
Thanks so much for the feedback @cedricbatailler! 🙌  We chatted and decided to: 

- link to [this discussion in the NIST book](https://www.itl.nist.gov/div898/handbook/prc/section4/prc43.htm)
- frame this as two-way analysis of variance (ANOVA)
