### ISSUE TITLE
Add back in examples that will not run locally

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#14]
I'm removing this example from our current working branch so I can continue to work on the Hugo site, and I cannot serve the site locally with it.

Let's add it back in later and try to troubleshoot this:
https://github.com/tidymodels/tidymodels.org/blob/examples/content/examples/experienced-bayesian-methods-comparing-models/index.Rmd

**Comment by apreshill** [comment]
Also running into the same error in another experienced example: 

https://github.com/tidymodels/tidymodels.org/blob/1e55fb1fbc516643e6a69c609131b58f375fbbee/content/examples/experienced-survivial-analysis/index.Rmd#L156-L159

```
Error in check_stanfit(stanfit) : 
  Invalid stanfit object produced please report bug
Error in dimnamesGets(x, value) : 
  invalid dimnames given for “dgCMatrix” object
```

**Comment by topepo** [comment]
For the time being, go ahead and remove/deactivate them

**Comment by apreshill** [comment]
List of removed:

+ https://github.com/tidymodels/tidymodels.org/tree/examples/content/examples/experienced-bayesian-methods-comparing-models/index.Rmd
+ https://github.com/tidymodels/tidymodels.org/tree/examples/content/examples/experienced-survivial-analysis/
+ https://github.com/tidymodels/tidymodels.org/tree/examples/content/examples/experienced-text-analysis
+ https://github.com/tidymodels/tidymodels.org/tree/examples/content/examples/intermediate-effect-encoding-with-embed
+ https://github.com/tidymodels/tidymodels.org/tree/examples/content/examples/intermediate-feature-embedding

**Comment by topepo** [comment]
So just about anything Stan-related 😞

**Comment by juliasilge** [comment]
We have added back some of these, and moved other content elsewhere. 👍
