### ISSUE TITLE
Find: 404 errors for modeldata pkg links in tables

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#141]
<img width="885" alt="Screen Shot 2020-04-22 at 9 50 50 AM" src="https://user-images.githubusercontent.com/12160301/80010101-c5f2f080-847e-11ea-8ef3-a207883dffe8.png">

The modeldata package doesn't have a pkgdown site, so all of [these links](https://www.tidymodels.org/find/all/) are 404 errors.

**Comment by topepo** [comment]
I'll make that this week and test it in the new domain `modeldata.tidymodels.org`

**Comment by topepo** [comment]
Fixed. Most of the urls have been switched at this point and the rest should be in a week.
