### ISSUE TITLE
404 error for some of the augment functions from broom

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidymodels/tidymodels.org-legacy#142]
I happened to click on some of the augment functions from broom and I'm getting a 404 error at e.g. https://broom.tidyverse.org/reference/ordinal_tidiers.html, https://broom.tidyverse.org/reference/lme4_tidiers.html, https://broom.tidyverse.org/reference/nlme_tidiers.html, etc. I couldn't quickly figure out a pattern for which ones are failing, these are just a few that did.

**Comment by juliasilge** [comment]
These were moved to broom.mixed so we need to update the HTML tables.
