### ISSUE TITLE
Idea: purl code from get started vignettes into an RStudio cloud project

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#15]
R scripts would probably be enough here + any external data files, if we could set up the project with all the required packages as the base.

**Comment by topepo** [comment]
That's a good idea. 

I wish there were ways to exclude chunks from purlation (being purlified?) or to better translate chunk names into comment headers

**Comment by apreshill** [comment]
We can exclude with `purl = FALSE`: https://bookdown.org/yihui/rmarkdown-cookbook/purl.html

**Comment by juliasilge** [comment]
Closed in the creation of [cloudstart](https://github.com/tidymodels/cloudstart/) and #184
