### ISSUE TITLE
Add button for RStudio Cloud link

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#164]
@dcossyleon @karaesmen

See svg buttons:
https://rstudio.github.io/thematic/
https://gt.rstudio.com/ (https://github.com/rstudio/gt/blob/master/man/figures/gt-test-drive.svg)

I think these should go at the bottom of each "Get Started" article's introduction section (right under the code chunk with all the packages).

Design-wise, maybe just tidymodels colors + fonts. I think I'm at max icon capacity ;)

**Comment by dcossyleon** [comment]
@apreshill What do you think about something that looks more like a traditional button? I think it might look more "clickable" to a user. I could make it into a shortcode.

![image](https://user-images.githubusercontent.com/29008894/83557150-24c87280-a4df-11ea-9148-a95078eabe14.png)

and on hover: 
![image](https://user-images.githubusercontent.com/29008894/83559224-365f4980-a4e2-11ea-8f5a-fee03b7e790a.png)

**Comment by apreshill** [comment]
I like the button-ness of this 😆  

I wonder if the wording on the actual button could be more consistent with the other sites, so maybe on the button the wording is "Test Drive on RStudio Cloud"? Then maybe the text could say: "Alternatively, open an interactive version of this article in your browser:"

Random aesthetic note- I think we've gone with sharp corners on the site (like the brackets around TOC), maybe button is square? Or does that take away from "button-ness" too much?

**Comment by dcossyleon** [comment]
Great, here's what the updated version will look like.

**To add the text + button, insert the following shortcode with the URL to the RStudio project inside the quotes:**

`{{< test-drive url=" " >}}`

![image](https://user-images.githubusercontent.com/29008894/83587084-2bc1a600-a51c-11ea-9779-115ed1010a93.png)
