### ISSUE TITLE
Search parsnip models - dropdown selections too big

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/tidymodels.org-legacy#168]
<img width="905" alt="Screen Shot 2020-05-23 at 5 35 43 PM" src="https://user-images.githubusercontent.com/14034784/82743135-e9c68200-9d1b-11ea-9ea7-cf525eff8e9f.png">

**Comment by apreshill** [comment]
😭 😭 would that I knew how to fix this! DT did not respond to any of my column width arguments. Maybe it is time to call in a DT pro on this one. Thanks for the nudge!

**Comment by topepo** [comment]
We could shorten them to "class" and "reg" for the table

**Comment by EmilHvitfeldt** [comment]
I feel like it is a little more general problem. it also wraps the packages
<img width="565" alt="Screen Shot 2020-05-24 at 5 30 37 PM" src="https://user-images.githubusercontent.com/14034784/82768518-61f87a80-9de4-11ea-8d8f-e8a75172b0dd.png">


I also took be to surprise that selection "classification" in the mode returns methods that can do classification and only classification.

**Comment by juliasilge** [comment]
The fix in #169 looks great to me; let's call this closed. 🚀
