### ISSUE TITLE
CSS wish list

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#17]
For @dcossyleon 

# General

- [x] add "back to top" chevron button in footer

- [x] fix the table row color in `params.toml` 

- [x] is the hover color here for `Tidymodels` too light?

<img width="1210" alt="Screen Shot 2020-03-22 at 1 57 03 PM" src="https://user-images.githubusercontent.com/12160301/77260416-222ae080-6c45-11ea-9f7b-3b9b02e29fd2.png">

# `start/` section

The flexboxes need help!

- [x] the magenta is kinda intense on this page 😬 

- [x] the left column needs to have a max width that is smaller than it is now (I'm ok with text wrapping),

- [x] the right column needs to have more space between the text and the divider line,

- [x] everything from left to right needs to add up to 1100 px across to match the flex container from the top navbar (to my eyes, there is overflow currently)

<img width="1181" alt="Screen Shot 2020-03-22 at 11 20 13 AM" src="https://user-images.githubusercontent.com/12160301/77257057-2e0ba800-6c2f-11ea-9e73-df45874fed6c.png">

- [x] my CSS for making the left sidebar sticky when you scroll is likely to be hacky-y, please feel free to fix!! 

- [x] maybe we could make some CSS for the active menu item on the left sidebar to be highlighted when active. I think I need to do Hugo work to make that happen, but maybe with either color or a left border like you did with https://stat545.com/

**Comment by dcossyleon** [comment]
@apreshill -- sounds good! 

Related to this list, what do you think about changing the header hierarchy on `packages/` so that the gray uppercase headers are H1s. Using that styling for H1s will also help tone down the intensity of magenta in `start/`.

![image](https://user-images.githubusercontent.com/29008894/77265335-d2630e00-6c72-11ea-8a97-9538feefb82c.png)

**Comment by apreshill** [comment]
That sounds really good!

**Comment by dcossyleon** [comment]
Great-- when I change `Packages/` H2s to H1s, they disappear from the TOC. I'm guessing this has to do with something related to the [sidebar.html ](https://github.com/tidymodels/tidymodels.org/blob/examples-layouts/themes/hugo-tourmaline/layouts/partials/sidebar.html)?

**Comment by apreshill** [comment]
Whoops no I think this has something to do with how Hugo processes the TOC:

https://gohugo.io/content-management/toc/

Looks like I may be able to override this:
https://gohugo.io/getting-started/configuration-markup/#table-of-contents

**Comment by dcossyleon** [comment]
Alright, I've covered most of these, but still need to: 
* [ ] Create table wrappers, so overflow of tables (and not whole page) can be scrolled right.
* [x] Fix which headers Hugo uses in TOC (re: previous comment).
* [x] Create new H2 styling for body and TOCs (e.g. Getting Started: Preprocess your data with recipes)

> # `start/` section
>* [ ]  the right column needs to have more space between the text and the divider line,
>* [x]  my CSS for making the left sidebar sticky when you scroll is likely to be hacky-y, please feel free to fix!!
* [x]  Hugo work to make CSS active menu item appear. (Some basic CSS is in place, but once it's working, I'd like to try some more creative styling :nail_care:)

> Random requests (not high priority)
>
> * Javascript anchor links here? (http://desiree.rbind.io/post/2019/bookdown-anchor-links/); maybe add to [base Hugo theme](https://github.com/rstudio/hugo-tourmaline)
> * Javascript copy/paste code chunks?

**Comment by dcossyleon** [comment]
@apreshill -- not sure whether CSS or HUGO (or both), but ...

- [x] Getting Started sidebar disappears entirely on mobile

**Comment by apreshill** [comment]
Can we add a "back to top" thingie? I think if we end up with all the articles in `learn` dumped in the same place, it might be nice:

<img width="1438" alt="Screen Shot 2020-03-30 at 11 42 34 AM" src="https://user-images.githubusercontent.com/12160301/77949370-b1ef1100-727b-11ea-85d8-77d29542596e.png">
