### ISSUE TITLE
Change column names for parsnip find tables

### ISSUE THREAD

**Issue by karaesmen** [tidymodels/tidymodels.org-legacy#172]
@apreshill @juliasilge While a "model" and "model object" can be quite ambiguous terms by nature, it would be nice to repeat certain terminology through out tidymodels to help learners make connections faster. In the start articles and in the parsnip vignette, three main terms are used while explaining a parsnip model: **model type**, **engine** and **mode**. It would be nice if the parsnip find tables reflected this terminology as well. I would suggest changing column name **TOPIC** in the "Explore Models" table to **MODEL TYPE**, similarly for "Explore Model Arguments" table using **MODEL TYPE** instead of **MODEL** would also be useful. But if length or space in the name is going to be an issue, at least both columns should match and be named **MODEL**

**Comment by karaesmen** [comment]
I had issues rendering the **index.Rmd** after making my changes to reflect the suggestion above.

Error can be seen below:

```
> blogdown:::serve_site()
Rendering content/find/parsnip/index.Rmd
Quitting from lines 12-33 (index.Rmd) 
Error: package or namespace load failed for 'plsmod' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'mixOmics'
Execution halted
Error in render_page(f) : 
  Failed to render 'content/find/parsnip/index.Rmd'
> install.packages("mixOmics")
Warning in install.packages :
  package ‘mixOmics’ is not available (for R version 4.0.0)
```

**Comment by apreshill** [comment]
Can you paste the code in here for what to change exactly?

**Comment by karaesmen** [comment]
I went with `rename()` for this, but could be changed within `DT::datatable` as well I'm sure. Just running the code chunks locally it looked fine with datatable in viewer pane.

In `content/find/parsnip/index.Rmd`

1.   In chunk `table-display`, after line 73:
```
pkg_urls %>% 
  mutate(
    package = as.factor(package),
    mode = as.factor(mode)
  ) %>%
  rename(`model type`=model ) %>%
  DT::datatable(
    rownames = FALSE,
    class = 'cell-border stripe',
    escape = FALSE,
    filter = "top",
    options = list(pageLength = 5)
  )
```

2. In chunk `params`, after line 104:
```
args <- 
  ls(envir) %>% 
  tibble(name = .) %>% 
  filter(str_detect(name, "args")) %>% 
  mutate(model = str_replace(name, "_args", ""),
         args  = map(name, ~envir[[.x]])) %>% 
  unnest(args) %>% 
  select(model:original) %>%
  rename(`model type`=topic )

DT::datatable(
  args, 
  rownames = FALSE,
  class = 'cell-border stripe',
  filter = 'top',
  escape = FALSE,
  options = list(pageLength = 5)
  )
```

**Comment by karaesmen** [comment]
Actually investigating further, `mixOmics` is available via Bioconductor only now and not CRAN. Can be installed with:

```
install.packages("BiocManager")
BiocManager::install("mixOmics")
```

When prompted in regards to `mixOmics` dependencies:
```
Update all/some/none? [a/s/n]: 
a
```
and
```
Do you want to install from sources the packages which need compilation? (Yes/no/cancel) no
```
`blogdown:::serve_site()` renders fine now!

**Comment by juliasilge** [comment]
We got this changed! 👍
