### ISSUE TITLE
Broken URLs in Website

### ISSUE THREAD

**Issue by jaredlander** [tidymodels/tidymodels.org-legacy#187]
The page for learning about models (https://www.tidymodels.org/find/parsnip/) provides broken links in the "Model Type" column of the "Explore Models" table. For instance, `decision_tree` links to https://parsnip.tidymodels.org/referencedecision_tree.html which is missing a `/` after reference and should be https://parsnip.tidymodels.org/reference/decision_tree.html.

**Comment by juliasilge** [comment]
Thank you so much for the report @jaredlander! 🙌
