### ISSUE TITLE
Follow tidyverse style guide for naming packages

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#19]
> "Do not use code font for package names. If the package name is ambiguous in the context, disambiguate with words, e.g. “the foo package”. Do not capitalize the function name if it occurs at the start of a sentence."

https://style.tidyverse.org/documentation.html#r-code

Pages/sections:

- [x] landing page
- [x] packages
- [x] start
- [x] learn
- [x] help
- [x] contribute

**Comment by topepo** [comment]
Noooooo! 

( also @DavisVaughan )

**Comment by apreshill** [comment]
I'll let you all take this issue up with the powers that be. Let me know 👍

**Comment by topepo** [comment]
I'll make the changes 😞

**Comment by topepo** [comment]
Fixed in #29
