### ISSUE TITLE
Typo in subsampling for class imbalances

### ISSUE THREAD

**Issue by robinsones** [tidymodels/tidymodels.org-legacy#203]
On [the page about subsampling for class imbalances](https://www.tidymodels.org/learn/models/sub-sampling/), 0.05 should be 0.5:

> The area under the ROC curve is an overall assessment of performance across all cutoffs. Values near one indicate very good results while values near 0.05 would imply that the model is very poor.

**Comment by juliasilge** [comment]
Thank you so much for the report @robinsones! 🙌  I've got that typo fixed in the PR updating the website for new package versions and such.
