### ISSUE TITLE
Use {svglite} for figures?

### ISSUE THREAD

**Issue by hfrick** [tidymodels/tidymodels.org-legacy#213]
The idea is by @juliasilge, I'm just putting it into an issue.

**Comment by juliasilge** [comment]
I believe that in `/start` and `/learn`, we need to change the device in `common.R` and then do a major re-render. This _is_ a good idea, though, so we use actual fonts/text for the text instead of R drawing the text as images.

**Comment by juliasilge** [comment]
I believe we handled all the images in previous PRs. ⬆️
