### ISSUE TITLE
Consider adding tz = "America/New_York" to data setup in Recipes Get Started page

### ISSUE THREAD

**Issue by Rmadillo** [tidymodels/tidymodels.org-legacy#222]
Not a bug but a small "gotcha" in the setup of the _Recipes_ section of the **Get Started** vignettes (tidymodels.org/content/start/recipes/index.Rmarkdown): `as.Date` automatically assumes UTC time, so in that part of the mutate step, the evening flights are moved to the next calendar day. You have to explicitly specify the time zone to ensure the date stays the same. Probably doesn't matter much for this purpose/example, but seems like a good practice to show/share. 

I picked row 760 arbitrarily as an example:

```
flights$time_hour[760]
# [1] "2013-01-01 20:00:00 EST"
as.Date(flights$time_hour[760])
# [1] "2013-01-02"
trunc(flights$time_hour[760], "days")
# [1] "2013-01-01 EST"
as.Date(flights$time_hour[760], tz = "America/New_York")
# [1] "2013-01-01"
```

So, please consider changing row 61/62 to something like:

```
flight_data <- 
  flights %>% 
  mutate(
    # Convert the arrival delay to a factor
    arr_delay = ifelse(arr_delay >= 30, "late", "on_time"),
    arr_delay = factor(arr_delay),
    # We will use the date (not date-time) in the recipe below, so we need to specify the time zone
    date = as.Date(time_hour, tz = "America/New_York")
```

**Comment by juliasilge** [comment]
Another option is to use `lubridate::as_date()`, which [keeps the timezone of the original object](https://lubridate.tidyverse.org/reference/as_date.html#arguments):

``` r
library(nycflights13)

flights$time_hour[760]
#> [1] "2013-01-01 20:00:00 EST"

lubridate::as_date(flights$time_hour[760])
#> [1] "2013-01-01"
```

<sup>Created on 2021-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
