### ISSUE TITLE
why do footnotes not look like footnotes?

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#23]
<img width="806" alt="Screen Shot 2020-03-23 at 8 41 57 PM" src="https://user-images.githubusercontent.com/12160301/77385990-e9733000-6d46-11ea-9e86-f67b696fc72e.png">

**Comment by apreshill** [comment]
Looks like this could be set to true in the `config.toml` file:

```
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
```

https://gohugo.io/getting-started/configuration-markup/#configure-markup

**Comment by apreshill** [comment]
https://github.com/yuin/goldmark/blob/master/extension/_test/footnote.txt

https://github.com/gohugoio/hugo/issues/6551

https://danielpost.com/articles/making-hugos-footnotes-accessible/

https://www.sitepoint.com/accessible-footnotes-css/

**Comment by apreshill** [comment]
OK, this is solved currently in a branch. The markdown syntax is slightly different for footnotes:

```
That's some text with a footnote.[^1]

[^1]: And that's the footnote.
```

And I added this to the CSS:
```
sup {
  vertical-align: super;
  font-size: smaller;
}
```

**Comment by juliasilge** [comment]
NO MORE FOOTNOTES 🙅
