### ISSUE TITLE
Missing library in step_umap 'Examples' section

### ISSUE THREAD

**Issue by exsell-jc** [tidymodels/tidymodels.org-legacy#238]
I could not find the file for `step_umap.html`

https://embed.tidymodels.org/reference/step_umap.html#examples-1

It needs `library(embed)`

**Comment by hfrick** [comment]
Our policy is to assume you have the package loaded to which the function belongs (for which you are looking at the help page of). So for any of the steps in embed, you won't see a `library(embed)`.

**Comment by juliasilge** [comment]
Just to clarify here again, this is how documentation in R works (base R, not our decision). When you look at a help page for a function from a certain package, the code you see assumes you have the package built and loaded. Good luck with your modeling tasks! 🙌
