### ISSUE TITLE
List `shinymodels` on `/packages`

### ISSUE THREAD

**Issue by hfrick** [tidymodels/tidymodels.org-legacy#245]
shinymodels isn't listed yet. The section "Tune, compare, and work with your models" of https://www.tidymodels.org/packages/#specialized-packages seems like a good place

**Comment by juliasilge** [comment]
Also:

- workflowsets, which probably should go just below/above stacks
- finetune, which also should go somewhere around stacks

I'd vote for shinymodels lower on the list, maybe at the end?
