### ISSUE TITLE
Include custom tranformations for dials objects

### ISSUE THREAD

**Issue by hfrick** [tidymodels/tidymodels.org-legacy#253]
Let's consider expanding the section on transformations in [the dials article](https://www.tidymodels.org/learn/develop/parameters/#quantitative-parameters) by also showing a custom transformation via `scales::trans_new()`. 

It would be good to explicitly show which functions go into the `transform` and `inverse` arguments to `trans_new()`. `new_quant_param()` expects `range` to be specified _in the transformed units_ (when a transformation is present) which needs to be kept in mind when choosing where to put which transformation function.

Along the lines of  https://github.com/tidymodels/dials/issues/238:
``` r
library(dials)
#> Loading required package: scales
library(magrittr)

# Custom tranformation
trans_raise <- trans_new(
  "raise", 
  transform = function(x) 2^x , 
  inverse = function(x) -log2(x)
)
custom_cost <- cost(range = c(1, 10), trans = trans_raise)
custom_cost
#> Cost (quantitative)
#> Transformer: raise [-Inf, Inf]
#> Range (transformed scale): [1, 10]
# sampled values cover the `range` specified on the transformed scale
-log2(c(1, 10))
#> [1]  0.000000 -3.321928
value_sample(custom_cost, 100) %>% range()
#> [1] -3.321564620 -0.004446303
```

<sup>Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by juliasilge** [comment]
I think this is a great idea, but this doc is oriented towards folks building their own custom dials parameter. It's probably more common for folks to be wanting to transform a regular, existing dials object. Can we explicitly show this somewhere in the dials docs themselves? Maybe the main vignette? It looks like tidymodels/dials#243 doesn't show how to do this, but instead adds text/description/words only.

**Comment by hfrick** [comment]
This got added to the dials main vignette in https://github.com/tidymodels/dials/pull/244
