### ISSUE TITLE
update qualitative parameters section

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/tidymodels.org-legacy#270]
This section https://www.tidymodels.org/learn/develop/parameters/#qualitative-parameters is slightly out of date as the `default` argument of `new_qual_param` is deprecated. @hfrick can you take a look at this and submit a PR to fix it? You don't need to rerender anything, I'll merge it into https://github.com/tidymodels/tidymodels.org/pull/269 and render it there.

``` r
library(dials)

aggregation <- function(values = c("none", "min", "max", "mean", "sum")) {
  new_qual_param(
    type = "character",
    values = values,
    # By default, the first value is selected as default. We'll specify that to
    # make it clear.
    default = "none",
    label = c(aggregation = "Aggregation Method")
  )
}

aggregation()
#> Warning: The `default` argument of `new_qual_param()` is deprecated as of dials
#> 1.0.1.
#> Aggregation Method  (qualitative)
#> 5 possible values include:
#> 'none', 'min', 'max', 'mean' and 'sum'
```

<sup>Created on 2022-11-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hfrick** [comment]
@EmilHvitfeldt should I open a PR for your `rerender2` branch (for #269) instead of `main`?

**Comment by EmilHvitfeldt** [comment]
sure!
