### ISSUE TITLE
fix hex sizes

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#32]
<img width="221" alt="Screenshot 2020-03-30 at 18 49 44" src="https://user-images.githubusercontent.com/12160301/77946178-c5e44400-7276-11ea-9c92-6de83269cb30.png">

@dcossyleon

**Comment by dcossyleon** [comment]
Packages page only -- this  also happens the [tidyverse.org site](https://www.tidyverse.org/packages/). Maybe we should change the theme?

**Comment by apreshill** [comment]
Yes, here is where we should do the fix: https://github.com/rstudio/hugo-tourmaline/tree/master/static/css/images

**Comment by topepo** [comment]
and get the proper `tune` hex 😄

**Comment by apreshill** [comment]
proper tune hex closed in https://github.com/tidymodels/tidymodels.org/pull/70

I'm closing this issue here as it is in the original tidyverse theme: https://github.com/rstudio/hugo-tourmaline/issues/17
