### ISSUE TITLE
add MathJax

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/tidymodels.org-legacy#36]
Looks like MathJax isn't turned on yet in the appropriate spot. Some of the infer articles (such as `infer-tables`) are good place to check that this is working.

**Comment by apreshill** [comment]
https://github.com/yihui/hugo-xmag/blob/369c49fc4cbd11109773895151edce464de7eded/layouts/partials/footer.html#L17-L20

**Comment by apreshill** [comment]
So it is actually in there- I'm not sure why not working:

https://github.com/tidymodels/tidymodels.org/blob/master/themes/hugo-tourmaline/layouts/partials/footer_mathjax.html

Edit: I'm not sure I see where it is not working. @juliasilge here is the article you mentioned, am I missing it?
https://deploy-preview-38--goofy-kowalevski-f8316d.netlify.com/learn/statistics/infer-tables/

**Comment by apreshill** [comment]
Looks like this might be a VPN issue
