### ISSUE TITLE
customize "event" sticky

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#39]
@dcossyleon 

https://github.com/tidymodels/tidymodels.org/blob/2b97b25aebe460f162425900db1c7703f10c0a9e/themes/hugo-tourmaline/static/css/main-site.css#L1136-L1165

To fit with current color theme, we want to customize these "stickies"

Visible here on the right sidebar for "upcoming events":
https://education.rstudio.com/blog/

**Comment by dcossyleon** [comment]
@apreshill what do you think about something like this?

![image](https://user-images.githubusercontent.com/29008894/78320550-b5aebc00-7537-11ea-81b7-7b3d35f0a999.png)

**Comment by apreshill** [comment]
@dcossyleon would it be possible to add in that awesome blue gray you put on the home page? Either in the colors for the sticky or the text?

**Comment by dcossyleon** [comment]
What do you think of one of these 3?

![image](https://user-images.githubusercontent.com/29008894/78366086-018c5000-758e-11ea-830c-919f8af52c09.png)

![image](https://user-images.githubusercontent.com/29008894/78366916-406ed580-758f-11ea-8cbf-f71213b26d39.png)


![image](https://user-images.githubusercontent.com/29008894/78366765-fb4aa380-758e-11ea-9919-4d6764198350.png)

**Comment by apreshill** [comment]
do you have a favorite? I like (2) but maybe mainly b/c no outline all the way around.

**Comment by dcossyleon** [comment]
I don't have a fave, but my least favorite is 3 because I think the dark color draws gives it too much weight for a minor element on the page. 

we can try this combo for now (similar to 2, but uses same gray as on home page) and see if after a couple of days we still like it 
![image](https://user-images.githubusercontent.com/29008894/78378861-90559880-759f-11ea-924f-85de44b70da2.png)

**Comment by apreshill** [comment]
What about this with the pale pink background?

**Comment by dcossyleon** [comment]
Same thing, but with light pink background. ![image](https://user-images.githubusercontent.com/29008894/78379856-073f6100-75a1-11ea-974f-4688cf615a38.png)

And I then I tried the light pink background with a much lighter gray bar at the top, and I think this one might be my favorite -- what do you think?
![image](https://user-images.githubusercontent.com/29008894/78380154-6c935200-75a1-11ea-9e1a-1f5a7e6425df.png)

**Comment by apreshill** [comment]
I agree- last one is my favorite.
