### ISSUE TITLE
"get started" articles TOC

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#41]
@dcossyleon 

We currently have a bulleted TOC list:

<img width="803" alt="Screen Shot 2020-04-02 at 3 35 30 PM" src="https://user-images.githubusercontent.com/12160301/78306197-a4de5600-74f7-11ea-919c-1fae6b1d403d.png">

I'd love to see lines or a box kind of like this (not exactly like this- I like the bullets and colors we have, but the lines help.):
<img width="1589" alt="Screen Shot 2020-04-02 at 3 34 59 PM" src="https://user-images.githubusercontent.com/12160301/78306241-bde70700-74f7-11ea-9577-7e61bbc196f1.png">

**Comment by dcossyleon** [comment]
One idea: 
![image](https://user-images.githubusercontent.com/29008894/78389097-285b7e00-75b0-11ea-9556-0183991eaf15.png)

**Comment by apreshill** [comment]
I think I'm going to make these docs into .Rmarkdown to make this a bit easier to style, but I really like this. You could assume that it will work the exact same way then as the TOC in the learn sections (in terms of Hugo).

EDITED TO ADD: now here
https://github.com/apreshill/tidymodels.org/tree/start-style

**Comment by apreshill** [comment]
Now in the `master` branch.
