### ISSUE TITLE
Emphasize model and recipe/pre-process as a bundle in resampling/tune "Get Started" articles

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#42]
Hi @juliasilge and @topepo,

After reviewing the "Get Started" section (which is awesome!), I'd like to propose that we switch the order or recipes and resampling. A few reasons:

1. recipes also introduces workflows. But then resampling doesn't use recipes or workflows. It would be nice to use the articles to reinforce concepts introduced already, and build up the packages introduced incrementally (rather than leaving them behind).

1. resampling doesn't currently include recipes or rely on it in any way, so it could easily be moved up. This would then free up the recipes article to showcase how easy it is to add a recipe when doing resampling in the tidymodels framework.

I think the sequential nature of how we are presenting these vignettes gives you more freedom than in a pkgdown vignette/blog-post style to really teach the packages and workflows as they are designed to be used, especially as those code examples are not easy to find elsewhere (via pkgdown sites or anywhere else on this site).

**Comment by topepo** [comment]
I think that the current order is appropriate, even with these discontinuities. I really want to impress that the model and recipe/pre-process should be thought of as a bundle that goes into resampling. 

Maybe we could change these by using workflows more? Would that address your concerns? 

Also, once TMwR is live, I want to add some conceptual notes to these articles (as footnotes) that (hopefully) doesn't get in the way of the content.

**Comment by apreshill** [comment]
> I really want to impress that the model and recipe/pre-process should be thought of as a bundle that goes into resampling.

In this case, I suggest that the resampling article includes a recipe and a workflow.

**Comment by juliasilge** [comment]
I agree with Max that the recipes article should come before resampling; we'll work on editing that resampling article so that it builds more.

One other thing to keep in mind is that the final case study will have **all** the pieces put together: recipe, model, tuning, etc.

**Comment by apreshill** [comment]
I think more continuity would help. Tune also doesn't use a recipe or a workflow. I would try not to rely too much on the case study as a final integration, and rather build integration throughout so that each concept is reinforced. This has two purposes. One, you help your learners remember better. Two, you help motivate your learners- people feel good and are more likely to stick with it when they feel like they are getting it. Learning about recipes/workflows in article 2 then not seeing them again until article 5 leaves a pretty large gap between concepts.

**Comment by topepo** [comment]
I'll make these changes. Is there a branch that I should be working off of?

**Comment by apreshill** [comment]
I'll be doing PRs to master soon, but for now master is good enough!
