### ISSUE TITLE
"Learn" page section thumbnails

### ISSUE THREAD

**Issue by dcossyleon** [tidymodels/tidymodels.org-legacy#48]
The best option may be to keep things small and close to the section title, perhaps using an image that is more akin to an icon instead of a thumbnail (e.g. [these icons](https://www.flaticon.com/?utm_term=%2Bicon&utm_campaign=US_ING_GO_SE_GENERIC_BRO_Tr%C3%A1fico_Icons&utm_source=adwords&utm_medium=ppc&hsa_acc=5490559948&hsa_cam=9603503984&hsa_grp=105829555344&hsa_ad=425008200652&hsa_src=g&hsa_tgt=kwd-3100280789&hsa_kw=%2Bicon&hsa_mt=b&hsa_net=adwords&hsa_ver=3&gclid=EAIaIQobChMIstKDg9TN6AIVrP_jBx2_WwzmEAAYAiAAEgIE4_D_BwE))

1) 
<img width="1298" alt="Screen Shot 2020-04-03 at 9 43 21 PM" src="https://user-images.githubusercontent.com/29008894/78416152-d6891700-75f4-11ea-8054-e4db89866adf.png">

2) (imagine this with the article titles indented, so that the pink article titles are aligned with the Section Header)
<img width="1177" alt="Screen Shot 2020-04-03 at 9 16 18 PM" src="https://user-images.githubusercontent.com/29008894/78416153-da1c9e00-75f4-11ea-828c-96c33ac80d84.png">

3) 
<img width="1231" alt="Screen Shot 2020-04-03 at 9 00 36 PM" src="https://user-images.githubusercontent.com/29008894/78416155-e0ab1580-75f4-11ea-9b76-7830fc6c06ba.png">

4) something similar to the original design of the [education website's learn page ](https://education.rstudio.com/learn/), where there was a larger image with white background above each section.

**Comment by juliasilge** [comment]
I like option 1 here a lot, perhaps with the thumbnail/icon a bit smaller (or square) so the title / objective text take up more of the width of the page.

**Comment by juliasilge** [comment]
I don't think it needs to say "Learning objective" a bunch of times; I think those can exist as basically quasi-description fields under each title.

**Comment by apreshill** [comment]
@juliasilge answered my next question- thanks!

**Comment by topepo** [comment]
I like using the left-hand side in numero 1. Is there an image that's more about statistics/data analysis that we can use?

**Comment by juliasilge** [comment]
This [icon pack](https://www.flaticon.com/packs/data-science-17) would be perfect, if it's appropriate for our use.

- `learn/statistics`: [probability](https://www.flaticon.com/free-icon/probability_2103656)
- `learn/models`: [machine learning](https://www.flaticon.com/free-icon/machine-learning_2103626) or [linear regression](https://www.flaticon.com/free-icon/linear-regression_2103610)
- `learn/work`: [data](https://www.flaticon.com/free-icon/data_2103565)
- `learn/developer`: [toolbox](https://www.flaticon.com/free-icon/toolbox_2103676) or maybe the friendly head in [machine learning](https://www.flaticon.com/free-icon/machine-learning_2103626)

**Comment by apreshill** [comment]
This is now in the `master` branch; thanks all!
