### ISSUE TITLE
Add sharing and twitter images

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#5]
This is new in the site theme, located in the `config/_default/params.toml` file currently in my PR #4 . You'll want a larger summary image for [twitter](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image):

> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

Might be a good request for our artist in residence? You can see our edu sharing image [here](https://github.com/rstudio/education.rstudio.com/tree/master/static/images).

    Recommended Dimensions: 876 x 438 px
    Minimum Dimensions: 280 x 150 px
    Allowed File Types: JPG, GIF, PNG
    Max File Size: 1 MB
    Image Scale: 2 x 1

**Comment by apreshill** [comment]
Edit here:  config/_default/params.toml

**Comment by juliasilge** [comment]
Let me know if you want this elsewhere, but it seems like it matches pretty closely:

Can we update the favicon?

**Comment by apreshill** [comment]
code to recreate hex curves
```
library(AppliedPredictiveModeling)
library(caret)
library(RColorBrewer)
library(tidymodels)
​
​
set.seed(2115)
two_class_dat <- quadBoundaryFunc(1000)
two_class_dat$X1 <- -two_class_dat$X1
​
extras1 <- tibble(
  X1 = rnorm(100, mean = -1, sd = .5),
  X2 = rnorm(100, mean = -1.25), sd = .5,
  class = "Class2"
)
​
extras2 <- tibble(
  X1 = rnorm(100, mean = -2, sd = .5),
  X2 = rnorm(100, mean = 2), sd = .5,
  class = "Class2"
)
​
two_class_dat <- bind_rows(two_class_dat, extras1, extras2)
​
ggplot(two_class_dat, aes(x =X2, y = X1, col = class)) + geom_point()
​
​
​
rng_1 <- extendrange(two_class_dat$X1)
rng_2 <- extendrange(two_class_dat$X2)
​
set.seed(1)
contour_grid <- expand.grid(X1 = seq(rng_1[1], rng_1[2], length = 200),
                            X2 = seq(rng_2[1], rng_2[2], length = 200))
​
two_class_ctrl_rand <- trainControl(method = "none", classProbs = TRUE,
                                    search = "random", 
                                    summaryFunction = twoClassSummary)
​
​
set.seed(235)
tt <- contour_grid
for(i in 1:10) {
  
  
  bt_version <- two_class_dat[sample(1:nrow(two_class_dat), replace = TRUE),]
  
  
​
  nn_fit <- train(class ~ X1 + X2,
                  data = bt_version,
                  method = "nnet",
                  tuneGrid = data.frame(size = 4, decay = 2),
                  trace = FALSE,
                  metric = "ROC",
                  trControl = two_class_ctrl_rand)
  
​
  tt[[paste0("nnet", i)]] <- predict(nn_fit, contour_grid, type ="prob")[,1]
}
​
​
p <- ggplot(tt, aes(x = X2, y = X1)) + 
  theme_bw()+
  theme(
    legend.position = "none",
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "black")
  )
​
cols <- brewer.pal(10, "Set1")
​
for(i in seq_along(cols))
  p <- 
  p + 
  geom_contour(
    aes_string(z = paste0("nnet", i)),
    breaks = .5,
    col = cols[i],
    lwd = .7,
    alpha = .4
  )
​
p <- p + theme_void() + theme_transparent()
​
library(hexSticker)
​
sticker(
  p,
  package = "tidymodels",
  p_size = 8,
  s_x = 1 ,
  s_y = 1.3,
  s_width = 1.9,
  s_height = 1,
  filename = "~/tmp/sticker.png",
  h_color = "#000000",
  h_fill = "#000000",
  p_color = "white", 
  p_x = 1, p_y = .6
)
​
svg("tidymodels_boundaries.svg", width = 5, height = 3)
print(p)
dev.off()
```

**Comment by apreshill** [comment]
I made a single sharing image in PR #93; see here:

<img width="991" alt="Screen Shot 2020-04-13 at 1 22 47 PM" src="https://user-images.githubusercontent.com/12160301/79157778-0de08c00-7d8a-11ea-89a7-388253f1cba9.png">

**Comment by apreshill** [comment]
Final version after a bit of tweaking
<img width="991" alt="Screen Shot 2020-04-13 at 2 03 28 PM" src="https://user-images.githubusercontent.com/12160301/79161058-b1806b00-7d8f-11ea-9ee9-c2221ad7dc57.png">
