### ISSUE TITLE
Update tidyverse.org "model" section

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#57]
<img width="1119" alt="Screen Shot 2020-04-09 at 5 14 41 PM" src="https://user-images.githubusercontent.com/12160301/78951073-a5419880-7a85-11ea-818f-c45c308bb6e9.png">

https://www.tidyverse.org/packages/#model

**Comment by juliasilge** [comment]
Updated! 🚀
