### ISSUE TITLE
add descriptions of non-core packages

### ISSUE THREAD

**Issue by topepo** [tidymodels/tidymodels.org-legacy#7]
In `content/packages/index.md`. Maybe a bulleted list.

**Comment by apreshill** [comment]
Added here: https://zealous-minsky-d250bd.netlify.com/packages/#specialized-packages

**Comment by apreshill** [comment]
On reflection, this list is a link dump. I wonder if we could organize these specialized packages to match the categories you have for the `learn` section articles? 

<img width="268" alt="Screen Shot 2020-03-23 at 6 43 44 AM" src="https://user-images.githubusercontent.com/12160301/77322916-b3479900-6cd1-11ea-8942-9d034ab1d99c.png">

**Comment by juliasilge** [comment]
Take a look here and [see what you think](https://julias-edits-thurs--zealous-minsky-d250bd.netlify.com/packages/#specialized-packages).
