### ISSUE TITLE
Add workflows

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#79]
It is in core tidymodels, currently missing from the `/packages/` page. Also needs a hex?

**Comment by topepo** [comment]
Yes. No hex right now. Should we make a "TBD" hex?

**Comment by juliasilge** [comment]
What is the typical turnaround on a hex from Greg? If this is somewhat high priority?

**Comment by apreshill** [comment]
I have requested a placeholder from Allison Horst/Greg S. to buy us some time.
