### ISSUE TITLE
Review/edit `data/` files

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#83]
Hi @topepo and @juliasilge,

There are now 2 data files in this Hugo site.

1. The [`resources.yaml`](https://github.com/tidymodels/tidymodels.org/blob/master/data/resources.yaml) populates the "Resources" stickies, which you can see [here](https://tidymodels-org.netlify.com/packages/) for example. Please review/edit.

1. The [`homepage.yaml`](https://github.com/tidymodels/tidymodels.org/blob/master/data/homepage.yaml) populates the homepage stickies in band 2, which you can see [here](https://tidymodels-org.netlify.com/). Please review/edit.

**Comment by juliasilge** [comment]
I think the homepage stickies look perfect as is. I just submitted a PR to edit the "Resources" stickies slightly (adding `/find` as a sticky).
